"""Step 3: write data/sample_raw_records.md — 5 complete raw records each from
Offers, Applications and Candidates, exactly as Airtable returned them.

Records are chosen deterministically (API order) so they can be traced by hand:
  Offers:       the first offer of each distinct Status, then the next offers
                in API order, up to 5.
  Applications: the applications linked to the first 3 sampled offers, plus
                the first `Rejected` and the first `Active` application with no offer.
  Candidates:   the candidates of those 5 applications (topped up in API
                order if two applications share a candidate).

Nothing is truncated or reformatted beyond JSON pretty-printing (indent=2,
key order as returned). The output contains personal data, so it is written
under data/ (git-ignored).

Usage:  python3 scripts/sample_records.py
"""
import json

from airtable_client import ROOT
from raw_data import load_manifest, load_records

OUT = ROOT / "data" / "sample_raw_records.md"
N = 5


def pick_offers(offers):
    chosen, seen_status = [], set()
    for o in offers:
        s = o["fields"].get("Status")
        if s not in seen_status:
            seen_status.add(s)
            chosen.append(o)
    for o in offers:
        if len(chosen) >= N:
            break
        if o not in chosen:
            chosen.append(o)
    return chosen[:N]


def pick_applications(apps, offers):
    by_id = {a["id"]: a for a in apps}
    chosen, why = [], {}
    for o in offers[:3]:
        a = by_id[o["fields"]["Application"][0]]
        chosen.append(a)
        why[a["id"]] = f"linked to offer {o['fields'].get('Offer ID')} ({o['fields'].get('Status')})"
    rules = [
        ("first `Rejected` application with no offer",
         lambda a: a["fields"].get("Stage") == "Rejected" and "Offers" not in a["fields"]),
        ("first `Active` application with no offer",
         lambda a: a["fields"].get("Status") == "Active" and "Offers" not in a["fields"]),
    ]
    for label, rule in rules:
        a = next(a for a in apps if rule(a) and a not in chosen)
        chosen.append(a)
        why[a["id"]] = label
    return chosen, why


def pick_candidates(cands, apps):
    by_id = {c["id"]: c for c in cands}
    chosen, why = [], {}
    for a in apps:
        c = by_id[a["fields"]["Candidate"][0]]
        if c not in chosen:
            chosen.append(c)
            why[c["id"]] = f"candidate on application {a['fields'].get('Application ID')}"
    for c in cands:
        if len(chosen) >= N:
            break
        if c not in chosen:
            chosen.append(c)
            why[c["id"]] = "top-up (API order)"
    return chosen[:N], why


def block(rec):
    return "```json\n" + json.dumps(rec, indent=2, ensure_ascii=False) + "\n```"


def main():
    manifest = load_manifest()
    offers_all = load_records("Offers")
    apps_all = load_records("Applications")
    cands_all = load_records("Candidates")

    offers = pick_offers(offers_all)
    offer_why = {o["id"]: f"Status `{o['fields'].get('Status')}`" for o in offers}
    apps, app_why = pick_applications(apps_all, offers)
    cands, cand_why = pick_candidates(cands_all, apps)

    sections = [
        ("Offers", "Offer ID", offers, offer_why),
        ("Applications", "Application ID", apps, app_why),
        ("Candidates", "Candidate ID", cands, cand_why),
    ]

    L = ["# Raw record samples: Offers, Applications, Candidates", ""]
    L += [
        f"Source: `data/raw/` snapshot fetched {manifest['started_at']}. Generated by "
        "`scripts/sample_records.py`.",
        "",
        "**Contains personal data. Local only: this file is git-ignored and must not be committed "
        "(the repo is public).**",
        "",
        "Each record is shown complete and untruncated, exactly as returned by the Airtable API "
        "(`id`, `createdTime`, `fields`), pretty-printed with the original key order.",
        "",
        "Things to keep in mind while reading:",
        "",
        "- Airtable **omits empty fields**. A field missing from a record means it is empty, "
        "not that the field does not exist.",
        "- Link fields are arrays of Airtable record IDs (`rec…`). Use the index below to follow "
        "offer → application → candidate.",
        "- Dates are `YYYY-MM-DD` strings. `createdTime` is the row-creation timestamp, not a business date.",
        "",
        "## Index",
        "",
        "| # | Table | Record ID | Business ID | Why selected | Links to |",
        "|---|---|---|---|---|---|",
    ]
    n = 0
    for table, key, recs, why in sections:
        for r in recs:
            n += 1
            f = r["fields"]
            links = []
            if table == "Offers":
                links.append(f"Application {f['Application'][0]}")
            if table == "Applications":
                links.append(f"Candidate {f['Candidate'][0]}")
                if "Offers" in f:
                    links.append(f"Offer {f['Offers'][0]}")
            if table == "Candidates":
                links.append("Applications " + ", ".join(f["Applications"]))
            L.append(f"| {n} | {table} | `{r['id']}` | {f.get(key, '—')} | {why[r['id']]} | "
                     f"{'; '.join(links)} |")
    L.append("")

    for table, key, recs, why in sections:
        L += [f"## {table} ({len(recs)} records)", ""]
        for r in recs:
            L += [f"### {table}: {r['fields'].get(key, r['id'])} (`{r['id']}`)", "",
                  f"Selected: {why[r['id']]}", "", block(r), ""]

    OUT.write_text("\n".join(L))
    print(f"wrote {OUT.relative_to(ROOT)} ({n} records)")


if __name__ == "__main__":
    main()
